glennreyes/react-countup

- package.json
> chore(package): update webpack-hot-middleware to version 2.12.2

- README.md
- package.json
- src/CountUp.jsx
re-submitting PR #34 with changes as suggested
> Add optional `redraw` prop

- .babelrc
- README.md
- package.json
- yarn.lock
> Add link to previous docs

- src/CountUp.js
> Add render prop check

- src/CountUp.js
Reverts glennreyes/react-countup#105
> Revert "Don't show instantiation  warning if valid react element"

- src/useCountUp.js
fixes https://github.com/glennreyes/react-countup/issues/113
> stop countup instance when unmounting component

- src/CountUp.js
> call the reset method when unmounting a component

- README.md
- src/CountUp.js
- src/__tests__/CountUp.test.js
- src/__tests__/__snapshots__/CountUp.test.js.snap
> Implement preserveValues feature

- src/CountUp.js
- src/__tests__/CountUp.test.js
Fix #155 
I suppose that we should reset current instance of Counter to fix this kinds of issues
> Reset counter when duration changed

- src/__tests__/CountUp.test.js
- src/__tests__/useCountUp.test.js
Add warning error test and some changes to useCountUp tests to hover more cases
> Add some tests

- src/CountUp.js
- src/__tests__/CountUp.test.js
> Fix updating countup with decimals and decimal

- index.d.ts
> Typescript hotfixes

- index.d.ts
> Fix hook types

- demo/package.json
- demo/src/App.js
- demo/yarn.lock
> Improve demo react-live styles

- README.md
- package.json
- src/CountUp.tsx
> Add initial start value for CountUp component

- src/CountUp.tsx
> Fix SSR condition

- .github/workflows/node.js.yml
- README.md
- demo/package.json
- demo/yarn.lock
- package.json
- rollup.config.js
- src/__tests__/CountUp.test.js
- src/__tests__/useCountUp.test.js
- src/common.ts
- src/useCountUp.ts
- yarn.lock
> Fix reset error

- package.json
- yarn.lock
> Bump CountUp

- src/types.ts
- src/useCountUp.ts
> useEasing defaults to undefined instead of true

- src/__tests__/CountUp.test.js
- src/tsconfig.json
- src/useCountUp.ts
> Fix undefined properties for wrapped components

- rollup.config.js
>  Exclude esm build
